[0;1;32m‚óè[0m gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
     Active: [0;1;32mactive (running)[0m since Wed 2023-06-07 05:40:40 UTC; 6s ago
TriggeredBy: [0;1;32m‚óè[0m gunicorn.socket
   Main PID: 23230 (gunicorn)
      Tasks: 4 (limit: 1116)
     Memory: 99.9M
        CPU: 1.151s
     CGroup: /system.slice/gunicorn.service
             ‚îú‚îÄ23230 /root/AnimePlay/backend/venv/bin/python /root/AnimePlay/backend/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock website.wsgi:application
             ‚îú‚îÄ23231 /root/AnimePlay/backend/venv/bin/python /root/AnimePlay/backend/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock website.wsgi:application
             ‚îú‚îÄ23232 /root/AnimePlay/backend/venv/bin/python /root/AnimePlay/backend/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock website.wsgi:application
             ‚îî‚îÄ23233 /root/AnimePlay/backend/venv/bin/python /root/AnimePlay/backend/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock website.wsgi:application

Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:     response = get_response(request)
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:   File "/root/AnimePlay/backend/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:     response = self.process_request(request)
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:   File "/root/AnimePlay/backend/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:     host = request.get_host()
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:   File "/root/AnimePlay/backend/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:     raise DisallowedHost(msg)
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]: django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]: Bad Request: /
Jun 07 05:40:41 pnqdgzqesm gunicorn[23231]:  - - [07/Jun/2023:10:40:41 +0500] "GET / HTTP/1.1" 400 59434 "-" "curl/7.81.0"
